-- V11: Create expert feedback table
-- 작업: GA_20260202_CREATIVE_REGISTRY_EXTENSION

CREATE TABLE IF NOT EXISTS expert_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL, -- Creative Asset ID
    evaluator_id BIGINT NOT NULL, -- 평가자 ID (기획사 또는 인증 평가자)
    evaluator_type VARCHAR(20) NOT NULL, -- AGENCY, CERTIFIED_EVALUATOR
    rating INTEGER, -- 1-5 점수
    comment TEXT,
    evidence_link VARCHAR(500), -- 증거 패키지 보기 링크 (레지스트리/에스크로 서비스에서 생성)
    is_public BOOLEAN NOT NULL DEFAULT true, -- 공개 여부 (true: 창작자 프로필 노출, false: 창작자만 확인)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_expert_feedback_asset ON expert_feedback(asset_id);
CREATE INDEX IF NOT EXISTS idx_expert_feedback_evaluator ON expert_feedback(evaluator_id);
CREATE INDEX IF NOT EXISTS idx_expert_feedback_created ON expert_feedback(created_at DESC);
