-- V9: Create audition stages table
-- 단계 정의 데이터를 통해 심사 단계 가변화

CREATE TABLE IF NOT EXISTS audition_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audition_id BIGINT NOT NULL,
    stage_number INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_audition_stage UNIQUE (audition_id, stage_number)
);

-- 기존 오디션에 기본 단계 생성 (1~max_rounds)
INSERT INTO audition_stages (audition_id, stage_number, name, created_at, updated_at)
SELECT a.id, s.stage_number, CONCAT('Round ', s.stage_number), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM auditions a
JOIN (
    SELECT 1 AS stage_number
    UNION ALL SELECT 2
    UNION ALL SELECT 3
) s ON s.stage_number <= a.max_rounds
WHERE NOT EXISTS (
    SELECT 1
    FROM audition_stages st
    WHERE st.audition_id = a.id
      AND st.stage_number = s.stage_number
);

CREATE INDEX IF NOT EXISTS idx_audition_stages_audition_id ON audition_stages(audition_id);
CREATE INDEX IF NOT EXISTS idx_audition_stages_stage_number ON audition_stages(stage_number);

