export const UPLOAD_ERROR = {
  NO_URL: 'UPLOAD_NO_URL',
  TIMEOUT: 'UPLOAD_TIMEOUT',
  FAILED: 'UPLOAD_FAILED',
  LOGIN_REQUIRED: 'UPLOAD_LOGIN_REQUIRED',
  FORBIDDEN: 'UPLOAD_FORBIDDEN',
  RATE_LIMITED: 'UPLOAD_RATE_LIMITED',
  TOO_LARGE: 'UPLOAD_TOO_LARGE',
} as const
