// ISO 3166-1 alpha-2 국가 코드 및 이름
export const countries = [
  { code: 'KR', name: '대한민국 (South Korea)' },
  { code: 'US', name: '미국 (United States)' },
  { code: 'JP', name: '일본 (Japan)' },
  { code: 'CN', name: '중국 (China)' },
  { code: 'GB', name: '영국 (United Kingdom)' },
  { code: 'FR', name: '프랑스 (France)' },
  { code: 'DE', name: '독일 (Germany)' },
  { code: 'IT', name: '이탈리아 (Italy)' },
  { code: 'ES', name: '스페인 (Spain)' },
  { code: 'CA', name: '캐나다 (Canada)' },
  { code: 'AU', name: '호주 (Australia)' },
  { code: 'BR', name: '브라질 (Brazil)' },
  { code: 'MX', name: '멕시코 (Mexico)' },
  { code: 'IN', name: '인도 (India)' },
  { code: 'RU', name: '러시아 (Russia)' },
  { code: 'TH', name: '태국 (Thailand)' },
  { code: 'VN', name: '베트남 (Vietnam)' },
  { code: 'PH', name: '필리핀 (Philippines)' },
  { code: 'ID', name: '인도네시아 (Indonesia)' },
  { code: 'SG', name: '싱가포르 (Singapore)' },
  { code: 'MY', name: '말레이시아 (Malaysia)' },
  { code: 'TW', name: '대만 (Taiwan)' },
  { code: 'HK', name: '홍콩 (Hong Kong)' },
]

export const languages = [
  { code: 'ko', name: '한국어' },
  { code: 'en', name: 'English' },
  { code: 'ja', name: '日本語' },
  { code: 'zh', name: '中文' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'th', name: 'ไทย' },
  { code: 'vi', name: 'Tiếng Việt' },
]

export const timezones = [
  { value: 'Asia/Seoul', label: 'Asia/Seoul (KST)' },
  { value: 'America/New_York', label: 'America/New_York (EST)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (PST)' },
  { value: 'America/Chicago', label: 'America/Chicago (CST)' },
  { value: 'Europe/London', label: 'Europe/London (GMT)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (HKT)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEDT)' },
]
