SET search_path TO public;

ALTER TABLE IF EXISTS public.users
  ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE IF EXISTS public.users
  ADD COLUMN IF NOT EXISTS profile_image_url TEXT;

ALTER TABLE IF EXISTS public.users
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
