-- V1: Create video_contents table (base for media-service)
-- V3 adds video_type, visibility; V4/V5 reference this table.

CREATE TABLE IF NOT EXISTS video_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    video_url VARCHAR(1000) NOT NULL,
    thumbnail_url VARCHAR(500),
    duration INTEGER,
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    category VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_video_contents_user_id ON video_contents(user_id);
CREATE INDEX IF NOT EXISTS idx_video_contents_category ON video_contents(category);
CREATE INDEX IF NOT EXISTS idx_video_contents_status ON video_contents(status);
