-- V2: Create creative assets table (Creative Vault)
-- 작업: GA_20260202_CREATIVE_REGISTRY_EXTENSION

CREATE TABLE IF NOT EXISTS creative_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    asset_type VARCHAR(50) NOT NULL, -- LYRIC, COMPOSITION, DEMO_AUDIO, VOCAL_GUIDE, STEMS, AI_GENERATED, AI_ASSISTED
    file_url VARCHAR(500), -- 파일 업로드인 경우
    text_content TEXT, -- 텍스트 입력인 경우 (가사 등)
    content_hash VARCHAR(64) NOT NULL, -- SHA-256 해시 (파일 또는 텍스트)
    file_size BIGINT,
    mime_type VARCHAR(100),
    declared_creation_type VARCHAR(50), -- HUMAN, AI_ASSISTED, AI_GENERATED
    access_control VARCHAR(20) NOT NULL DEFAULT 'PRIVATE', -- PUBLIC, AUDITION_ONLY, PRIVATE
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_creative_assets_user_id ON creative_assets(user_id);
CREATE INDEX IF NOT EXISTS idx_creative_assets_hash ON creative_assets(file_hash);
CREATE INDEX IF NOT EXISTS idx_creative_assets_access ON creative_assets(access_control);
CREATE INDEX IF NOT EXISTS idx_creative_assets_created ON creative_assets(created_at DESC);
