-- V4: Create video_feedback table (타임코드 기반 피드백)
-- 작업: 2026_13_video_feedback

CREATE TABLE IF NOT EXISTS video_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL, -- 피드백 작성자
    timestamp_seconds INTEGER NOT NULL, -- 타임코드 (초 단위)
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_video_feedback_video FOREIGN KEY (video_id) REFERENCES video_contents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_video_feedback_video ON video_feedback(video_id);
CREATE INDEX IF NOT EXISTS idx_video_feedback_user ON video_feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_video_feedback_timestamp ON video_feedback(video_id, timestamp_seconds);
