-- V5: Create video_comments table (영상 댓글)
-- 작업: 2026_21_community_features

CREATE TABLE IF NOT EXISTS video_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_comment_id BIGINT, -- 대댓글용 (NULL이면 최상위 댓글)
    content TEXT NOT NULL,
    like_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP, -- soft delete
    CONSTRAINT fk_video_comments_video FOREIGN KEY (video_id) REFERENCES video_contents(id) ON DELETE CASCADE,
    CONSTRAINT fk_video_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES video_comments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_video_comments_video ON video_comments(video_id);
CREATE INDEX IF NOT EXISTS idx_video_comments_user ON video_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_video_comments_parent ON video_comments(parent_comment_id);
