app:
  version: 1.0.0-SNAPSHOT
  buildId: ""
  cors:
    allowed-origins: "https://frontend-production-8613a.up.railway.app,http://localhost:3000"
  jwt:
    secret: "${JWT_SECRET:change-me-in-production-min-32-chars}"
    expiration-ms: 86400000  # 24h

spring:
  application:
    name: audition-platform-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/audition?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-init-sql: SET search_path TO public

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    default-schema: public
    create-schemas: true
    init-sqls: SET search_path TO public
    repair-on-migrate: true

server:
  port: 8080
