-- V11: Create user_follows table (팔로우/구독)
-- 작업: 2026_16_follow_subscription

CREATE TABLE IF NOT EXISTS user_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL, -- 팔로우하는 사용자
    following_id BIGINT NOT NULL, -- 팔로우 대상 (개인 채널 또는 기획사)
    follow_type VARCHAR(20) NOT NULL, -- CHANNEL(개인 채널), AGENCY(기획사)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_follows UNIQUE (follower_id, following_id, follow_type),
    CONSTRAINT fk_user_follows_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_follows_following FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_follows_follower ON user_follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_following ON user_follows(following_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_type ON user_follows(follow_type);
