-- V11: Create feedback sessions table

CREATE TABLE IF NOT EXISTS feedback_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    instructor_id BIGINT NOT NULL,
    request_message TEXT,
    response_message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_sessions_applicant_id ON feedback_sessions(applicant_id);
CREATE INDEX IF NOT EXISTS idx_feedback_sessions_instructor_id ON feedback_sessions(instructor_id);
CREATE INDEX IF NOT EXISTS idx_feedback_sessions_status ON feedback_sessions(status);

