-- V13: Create Stripe webhook events table

CREATE TABLE IF NOT EXISTS stripe_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(100),
    payload TEXT NOT NULL,
    signature VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_stripe_webhook_events_event_id ON stripe_webhook_events(event_id);

