-- V14: Create content_reports table (콘텐츠 신고)
-- 작업: OPS_02_content_moderation

CREATE TABLE IF NOT EXISTS content_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL, -- 신고자
    content_type VARCHAR(50) NOT NULL, -- VIDEO, COMMENT, USER 등
    content_id BIGINT NOT NULL, -- 신고 대상 콘텐츠 ID
    reason VARCHAR(100) NOT NULL, -- 신고 사유
    description TEXT, -- 상세 설명
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, REVIEWING, RESOLVED, REJECTED
    reviewed_by BIGINT, -- 검토자 (관리자)
    reviewed_at TIMESTAMP,
    resolution TEXT, -- 처리 결과
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_content_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_content_reports_type ON content_reports(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_content_reports_status ON content_reports(status);
CREATE INDEX IF NOT EXISTS idx_content_reports_reporter ON content_reports(reporter_id);
