-- V14: Create agency bookmarks table

CREATE TABLE IF NOT EXISTS agency_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    applicant_id BIGINT NOT NULL,
    memo TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agency_bookmarks_owner_applicant
    ON agency_bookmarks(owner_id, applicant_id);
CREATE INDEX IF NOT EXISTS idx_agency_bookmarks_owner_id ON agency_bookmarks(owner_id);
