-- V16: Create point_transactions table (포인트 거래 내역)
-- 작업: POINTS_01_system_design, POINTS_02_backend_points

CREATE TABLE IF NOT EXISTS point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    transaction_type VARCHAR(50) NOT NULL, -- CHARGE(충전), DEDUCTION(차감), REFUND(환불)
    amount BIGINT NOT NULL, -- 포인트 양 (양수: 충전, 음수: 차감)
    balance_before BIGINT NOT NULL, -- 거래 전 잔액
    balance_after BIGINT NOT NULL, -- 거래 후 잔액
    event_type VARCHAR(50), -- AUDITION_APPLICATION, CONTENT_ACCESS, STRIPE_TOPUP 등
    related_id BIGINT, -- 관련 엔티티 ID (오디션 ID, 콘텐츠 ID 등)
    description TEXT, -- 거래 설명
    stripe_payment_intent_id VARCHAR(255), -- Stripe 결제 ID (충전인 경우)
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED', -- COMPLETED, PENDING, FAILED, ROLLED_BACK
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_point_transactions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_point_transactions_user ON point_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_type ON point_transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_point_transactions_event ON point_transactions(event_type);
CREATE INDEX IF NOT EXISTS idx_point_transactions_created ON point_transactions(created_at DESC);
